services:
  database:
    image: postgres:17-alpine
    container_name: mooncode_postgres_db_container
    ports:
      - "5432:5432"
    volumes:
      - mooncode_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_USER: postgres
      - POSTGRES_DB: mooncode
volumes:
  mooncode_postgres:
    name: mooncode_postgres_db
